### ISSUE TITLE
investigate flaky tests

### ISSUE THREAD

**Issue by thomasballinger** [thomasballinger/rlundo#43]
Tests pass on Travis inconsistently - start adding failure as comments here.

**Comment by thomasballinger** [comment]
bcc0c4a

```
======================================================================
FAIL: test_initialize (test.test_rewrite.TestUndoScenario)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/thomasballinger/rlundo/test/test_rewrite.py", line 465, in test_initialize
    self.assertEqual(output, lines)
AssertionError: Lists differ: [u'$rw', u'>a', u'b', u'c', u'... != [u'$rw', u'>a', u'b', u'c', u'...
First list contains 2 additional elements.
First extra element 7:
uc1
- [u'$rw', u'>a', u'b', u'c', u'>d', u'e', u'>', u'uc1', u'up2']
?                                              ----------------
+ [u'$rw', u'>a', u'b', u'c', u'>d', u'e', u'>']
----------------------------------------------------------------------
```

**Comment by madelynfreed** [comment]
``` E.........E.E.E.........EEE.............E.....
======================================================================
ERROR: Failure: ImportError (No module named matplotlib.pyplot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/venv/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/venv/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/venv/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/memory_monitor.py", line 15, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot

======================================================================
ERROR: Recreating history in visible area because undo goes offscreen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/test_rewrite.py", line 246, in test_rewind_to_scrolled_off_prompt
    with TmuxPaneWithAddrsInEnv(70, 3) as t:
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/tmux.py", line 203, in __enter__
    wait_for_width(pane, self.width)
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/tmux.py", line 59, in wait_for_condition
    raise ValueError("contition was never true within max time: cond(%r, %r)" % (last, final))
ValueError: contition was never true within max time: cond(68, 70)

======================================================================
ERROR: test_scroll_down (test.test_rewrite.TestRunWithTmux)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/test_rewrite.py", line 187, in test_scroll_down
    with TmuxPaneWithAddrsInEnv(70, 8) as t:
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/tmux.py", line 203, in __enter__
    wait_for_width(pane, self.width)
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/tmux.py", line 59, in wait_for_condition
    raise ValueError("contition was never true within max time: cond(%r, %r)" % (last, final))
ValueError: contition was never true within max time: cond(68, 70)

======================================================================
ERROR: test_simple_save_and_restore (test.test_rewrite.TestRunWithTmux)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/test_rewrite.py", line 171, in test_simple_save_and_restore
    with TmuxPaneWithAddrsInEnv(70, 10) as t:
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/tmux.py", line 203, in __enter__
    wait_for_width(pane, self.width)
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/tmux.py", line 59, in wait_for_condition
    raise ValueError("contition was never true within max time: cond(%r, %r)" % (last, final))
ValueError: contition was never true within max time: cond(68, 70)

======================================================================
ERROR: Test sending commands and reading formatted output with tmux.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/test_rlundo.py", line 141, in test_simple
    with ActualUndo(70, 20) as t:
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/test_rlundo.py", line 81, in __enter__
    return tmux.TmuxPane.__enter__(self)
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/tmux.py", line 203, in __enter__
    wait_for_width(pane, self.width)
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/tmux.py", line 59, in wait_for_condition
    raise ValueError("contition was never true within max time: cond(%r, %r)" % (last, final))
ValueError: contition was never true within max time: cond(68, 70)

======================================================================
ERROR: Test undoing a line of a multiple lines command in ipython.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/test_rlundo.py", line 185, in test_undo_multiple_input_lines
    with ActualUndo(70, 20) as t:
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/test_rlundo.py", line 81, in __enter__
    return tmux.TmuxPane.__enter__(self)
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/tmux.py", line 203, in __enter__
    wait_for_width(pane, self.width)
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/tmux.py", line 59, in wait_for_condition
    raise ValueError("contition was never true within max time: cond(%r, %r)" % (last, final))
ValueError: contition was never true within max time: cond(68, 70)

======================================================================
ERROR: Test undoing one liner command in ipython.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/test_rlundo.py", line 163, in test_undo_simple
    with ActualUndo(70, 20) as t:
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/test_rlundo.py", line 81, in __enter__
    return tmux.TmuxPane.__enter__(self)
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/tmux.py", line 203, in __enter__
    wait_for_width(pane, self.width)
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/tmux.py", line 59, in wait_for_condition
    raise ValueError("contition was never true within max time: cond(%r, %r)" % (last, final))
ValueError: contition was never true within max time: cond(68, 70)

======================================================================
ERROR: test_initial_size (test.test_tmux.TestTmux)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/test_tmux.py", line 120, in test_initial_size
    with tmux.TmuxPane(70, 3) as t:
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/tmux.py", line 203, in __enter__
    wait_for_width(pane, self.width)
  File "/Users/madelynfreed/Documents/misc/Python/projects/rlundo/rlundo/test/tmux.py", line 59, in wait_for_condition
    raise ValueError("contition was never true within max time: cond(%r, %r)" % (last, final))
ValueError: contition was never true within max time: cond(68, 70)

----------------------------------------------------------------------
Ran 46 tests in 26.672s

FAILED (errors=8)
```

**Comment by thomasballinger** [comment]
e1a85eb

```
======================================================================
ERROR: test_resizing_window (test.test_rewrite.TestDiagramsWithTmux)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/thomasballinger/rlundo/test/test_rewrite.py", line 95, in test_resizing_window
    UndoScenario.initialize(t, termstate)
  File "/home/travis/build/thomasballinger/rlundo/test/test_rewrite.py", line 424, in initialize
    tmux.send_command(pane, '>', enter=False, prompt=u'>')
  File "/home/travis/build/thomasballinger/rlundo/test/tmux.py", line 149, in send_command
    wait_until_cursor_moves(pane, row, col)
  File "/home/travis/build/thomasballinger/rlundo/test/tmux.py", line 138, in wait_until_cursor_moves
    raise ValueError("cursor row didn't move from initial %r within max time: %r" % ((row, col), visible(pane)))
ValueError: cursor row didn't move from initial (5, 1) within max time: [u'usually 2', u'>2 + 2', u'notquite 4', u'>3', u'3', u'>']
```

**Comment by thomasballinger** [comment]
Added [flaky](https://github.com/box/flaky) to some of these tests, which should still display how flaky they were.
